version: "2"
services:
  node:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: bash -c "yarn install && node app.js"
    links:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db
